In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# load npy file
X_train = np.load('../data/X_train.npy')
y_train = np.load('../data/y_train.npy')

print(X_train.shape)
print(y_train.shape)
print(X_train[0])
print(y_train[0])

print(np.sum(y_train, axis=0))
print(np.sum(y_train, axis=1))

(24436, 1344, 4)
(24436, 2714)
[[0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]
 ...
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]]
[0 0 0 ... 0 0 0]
[4166 6589 6554 ... 5594 4987 7268]
[ 211 1111  167 ...  278  182  434]
